/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectounidad1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JRadioButton;



/**
 *
 * @author samuel
 */

public class PanelBuscarCliente extends javax.swing.JPanel {
    private VentanaPrincipal principal;
    /**
     * Creates new form PanelBuscarPedido
     */
    public PanelBuscarCliente(VentanaPrincipal principal) {
        initComponents();
        this.principal = principal;
        principal.rellenarSeleccionesBuscarCliente(comboPaises, listaCiudades);
        
        String consultaCargos = "SELECT NOMBRE FROM PUBLIC.CARGOS";
        try (PreparedStatement statement = principal.con.prepareStatement(consultaCargos);
             ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {
                String nombreCargo = resultSet.getString("NOMBRE");

                // Crear un JRadioButton para cada cargo
                JRadioButton radioButton = new JRadioButton(nombreCargo);

                // Agregar el JRadioButton al buttonGroup1
                String seleccion = resultSet.getString("NOMBRE");
                if(seleccion == null){
                    seleccion = "";
                }else{
                    radioButton.setActionCommand(seleccion);
                }
                
                buttonGroup1.add(radioButton);
                

                // Agregar el JRadioButton al panelBotones
                panelCargos.add(radioButton);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelFormularioBusqueda = new javax.swing.JPanel();
        companiaLabel = new javax.swing.JLabel();
        companiaTxt = new javax.swing.JTextField();
        codPostalLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        codPostalTxt = new javax.swing.JTextField();
        paisLabel = new javax.swing.JLabel();
        comboPaises = new javax.swing.JComboBox<>();
        ciudadLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCiudades = new javax.swing.JList<>();
        panelCargos = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        buscarBoton = new javax.swing.JButton();
        reiniciarBoton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 400));

        panelFormularioBusqueda.setPreferredSize(new java.awt.Dimension(1080, 220));

        companiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        companiaLabel.setText("Compañía");

        codPostalLabel.setText("Código postal");

        contactLabel.setText("Contacto");

        codPostalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPostalTxtActionPerformed(evt);
            }
        });

        paisLabel.setText("País");

        comboPaises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ciudadLabel.setText("Ciudad");

        listaCiudades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCiudades);

        javax.swing.GroupLayout panelFormularioBusquedaLayout = new javax.swing.GroupLayout(panelFormularioBusqueda);
        panelFormularioBusqueda.setLayout(panelFormularioBusquedaLayout);
        panelFormularioBusquedaLayout.setHorizontalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ciudadLabel)
                    .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(companiaLabel)
                                .addComponent(contactLabel)
                                .addComponent(codPostalLabel)))
                        .addComponent(paisLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(companiaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contactTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelFormularioBusquedaLayout.setVerticalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companiaLabel)
                    .addComponent(companiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPostalLabel))
                .addGap(26, 26, 26)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisLabel))
                .addGap(40, 40, 40)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudadLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCargos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));
        panelCargos.setLayout(new java.awt.GridLayout(5, 3, 20, 0));

        buscarBoton.setText("Buscar");
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        reiniciarBoton.setText("Reiniciar");
        reiniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
            principal.buscarCliente(codPostalTxt, companiaTxt, contactTxt, buttonGroup1, listaCiudades);
    }//GEN-LAST:event_buscarBotonActionPerformed

    private void reiniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarBotonActionPerformed
        buttonGroup1.clearSelection();
        comboPaises.setSelectedIndex(0);
        companiaTxt.setText("");
        contactTxt.setText("");
        codPostalTxt.setText("");
        principal.cargarTablaBuscarClientes();
    }//GEN-LAST:event_reiniciarBotonActionPerformed

    private void codPostalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPostalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPostalTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBoton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel ciudadLabel;
    private javax.swing.JLabel codPostalLabel;
    private javax.swing.JTextField codPostalTxt;
    private javax.swing.JComboBox<String> comboPaises;
    private javax.swing.JLabel companiaLabel;
    private javax.swing.JTextField companiaTxt;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCiudades;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCargos;
    private javax.swing.JPanel panelFormularioBusqueda;
    private javax.swing.JButton reiniciarBoton;
    // End of variables declaration//GEN-END:variables
}
