/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectounidad1;

import javax.swing.text.AbstractDocument;

/**
 *
 * @author samuel
 */

public class PanelBuscarPedido extends javax.swing.JPanel {
    private VentanaPrincipal principal;
    /**
     * Creates new form PanelBuscarPedido
     */
    public PanelBuscarPedido(VentanaPrincipal principal) {
        initComponents();
        this.principal = principal;
        principal.rellenarSeleccionesBuscar(empresaEnviosComboBox, ciudadPedidoComboBox, empleadoList);
        ((AbstractDocument) fpedidoTxt.getDocument()).setDocumentFilter(new DateDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormularioBusqueda = new javax.swing.JPanel();
        fpedidoLabel = new javax.swing.JLabel();
        fpedidoTxt = new javax.swing.JTextField();
        empEnvioLabel = new javax.swing.JLabel();
        empresaEnviosComboBox = new javax.swing.JComboBox<>();
        ciudadPedLabel = new javax.swing.JLabel();
        ciudadPedidoComboBox = new javax.swing.JComboBox<>();
        companiaLabel = new javax.swing.JLabel();
        companiaTxt = new javax.swing.JTextField();
        panelEmpleado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleadoList = new javax.swing.JList<>();
        empleadoLabel = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        buscarBoton = new javax.swing.JButton();
        reiniciarBoton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 400));

        panelFormularioBusqueda.setPreferredSize(new java.awt.Dimension(1080, 220));

        fpedidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpedidoLabel.setText("Fecha de pedido");

        empEnvioLabel.setText("Empresa de envío");

        empresaEnviosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ciudadPedLabel.setText("Ciudad del pedido");

        ciudadPedidoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        companiaLabel.setText("Nombre de la compañia cliente");

        javax.swing.GroupLayout panelFormularioBusquedaLayout = new javax.swing.GroupLayout(panelFormularioBusqueda);
        panelFormularioBusqueda.setLayout(panelFormularioBusquedaLayout);
        panelFormularioBusquedaLayout.setHorizontalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(fpedidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioBusquedaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(companiaLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(fpedidoTxt))
                .addGap(39, 39, 39)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ciudadPedLabel)
                    .addComponent(empEnvioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ciudadPedidoComboBox, 0, 84, Short.MAX_VALUE)
                    .addComponent(empresaEnviosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormularioBusquedaLayout.setVerticalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpedidoLabel)
                    .addComponent(fpedidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudadPedLabel)
                    .addComponent(ciudadPedidoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companiaLabel)
                    .addComponent(companiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empEnvioLabel)
                    .addComponent(empresaEnviosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        empleadoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(empleadoList);

        empleadoLabel.setText("Empleado");

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleadoLabel))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(empleadoLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        buscarBoton.setText("Buscar");
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        reiniciarBoton.setText("Reiniciar");
        reiniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
          principal.buscarPedido(empresaEnviosComboBox, ciudadPedidoComboBox, fpedidoTxt, companiaTxt, empleadoList);
    }//GEN-LAST:event_buscarBotonActionPerformed

    private void reiniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarBotonActionPerformed
        reiniciar();
    }//GEN-LAST:event_reiniciarBotonActionPerformed

    public void reiniciar(){
        ciudadPedidoComboBox.setSelectedIndex(0);
        empresaEnviosComboBox.setSelectedIndex(0);
        fpedidoTxt.setText("");
        companiaTxt.setText("");
        empleadoList.clearSelection();
        principal.cargarTablaBuscar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBoton;
    private javax.swing.JLabel ciudadPedLabel;
    private javax.swing.JComboBox<String> ciudadPedidoComboBox;
    private javax.swing.JLabel companiaLabel;
    private javax.swing.JTextField companiaTxt;
    private javax.swing.JLabel empEnvioLabel;
    private javax.swing.JLabel empleadoLabel;
    private javax.swing.JList<String> empleadoList;
    private javax.swing.JComboBox<String> empresaEnviosComboBox;
    private javax.swing.JLabel fpedidoLabel;
    private javax.swing.JTextField fpedidoTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelFormularioBusqueda;
    private javax.swing.JButton reiniciarBoton;
    // End of variables declaration//GEN-END:variables
}
